version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - kafka-net

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - kafka-net

  sensor-simulation:
    build: ./sensor-simulation
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    networks:
      - kafka-net
    deploy:
      replicas: 3 
      restart_policy:
        condition: on-failure

  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8081:8080" # Spark Master UI port
      - "7077:7077" # Spark Master Port
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "SPARK_MODE=master"
      - "SPARK_MASTER_HOST=spark-master"
    networks:
      - kafka-net

  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-1
    ports:
      - "8082:8081" # Spark Worker UI port
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=1g"
    depends_on:
      - spark-master
    networks:
      - kafka-net

  spark-submit:
    image: bde2020/spark-submit:3.1.1-hadoop3.2
    container_name: spark-submit
    depends_on:
      - spark-master
      - spark-worker-1
    volumes:
      - ./spark_processing.py:/opt/spark-processing/spark_processing.py
    #entrypoint: ["/bin/bash", "-c", "/spark/bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.1 --master spark://spark-master:7077 /opt/spark-processing/spark_processing.py"]   
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    networks:
      - kafka-net

  consumer:
    build: ./message-collector
    depends_on:
      - kafka
    volumes:
      - ./message-collector:/app
    networks:
      - kafka-net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - kafka-net
  
  storer:
    build: ./message-storer
    depends_on:
      - mongo
      - kafka
    volumes:
      - ./message-storer:/app
    networks:
      - kafka-net
  

networks:
  kafka-net:
