version: '3.8'
services:
  spark-master:
    image: bde2020/spark-master:3.1.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080" # Spark Master UI
      - "7077:7077" # Spark Master Port
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - "SPARK_MODE=master"
      - "SPARK_MASTER_HOST=spark-master"

  spark-worker-1:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-1
    ports:
      - "8081:8081" # Spark Worker UI
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=2g"
    depends_on:
      - spark-master

  spark-worker-2:
    image: bde2020/spark-worker:3.1.1-hadoop3.2
    container_name: spark-worker-2
    ports:
      - "8082:8081" # Spark Worker UI
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=2"
      - "SPARK_WORKER_MEMORY=2g"
    depends_on:
      - spark-master

  spark-submit:
    image: bde2020/spark-submit:3.1.1-hadoop3.2
    container_name: spark-submit
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
